export const options = ["Sprint log-Total Points Commited This Sprint",
                 "Sprint log-Total Points Spent This Sprint",
                //  "Sprint log-Individual Points Commited This Sprint",
                //  "Sprint log-Individual Points Spent This Sprint (MidSprint)",
                //  "Sprint log-Individual Points Commited-All Sprints",
                //  "Sprint log-Individual Points Spent-All Sprint",
                 "Sprint log-D T and R Points Breakdown",
                 "Sprint log-Summary of Stories", 
                 "Sprint log-Summary of Tasks", 
                 'PRC-link to PRC',
                //  "Sprint log-Last Edited",
                 "Sprint log-Riskiest Risk Specified in Planning View",
                 "Sprint log-Canvases Planned to Update Last Week",
                 "Link to Sprint Log",
                //  "PRC-Specific Slides (Under construction)",
                 "PRC-Time Last Edited",
                 "PRC-Slides Updated in this sprint",
                //  "Github-Number of Lines Code Committed this sprint (Under construction)",
                //  "Github-Number of Branches Created this sprint (Under construction)",
                //  "Github-Summary of Commits made this sprint (Under construction)"
            ]